#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DIST_DIR="${ROOT_DIR}/dist"
APP_NAME="Adventurers"
APP_DIR="${DIST_DIR}/${APP_NAME}.app"
VERSION="${1:-1.0.0}"

# Sparkle auto-update feed. SPARKLE_PUBLIC_KEY is the EdDSA public key (base64) generated by
# Sparkle's `generate_keys` tool — see docs/updating.md. It is safe to commit/bake into the app;
# only the matching private key (used in CI to sign each release, never checked into the repo)
# needs to stay secret.
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-https://github.com/4cecoder/adventurers-harness/releases/download/latest/appcast.xml}"
SPARKLE_PUBLIC_KEY="${SPARKLE_PUBLIC_KEY:-}"
if [ -z "${SPARKLE_PUBLIC_KEY}" ]; then
    echo "⚠️  SPARKLE_PUBLIC_KEY is not set — packaging without update-signature verification configured."
    echo "    Run './scripts/sparkle_tools.sh generate_keys' once (see docs/updating.md), then set"
    echo "    SPARKLE_PUBLIC_KEY to the public key it prints and store the private key for CI signing."
fi

echo "========================================================="
echo "🚀 Adventurers Harness macOS ARM64 Build & Packager v${VERSION}"
echo "========================================================="

# Step 1: Ensure icons are built
if [ ! -f "${ROOT_DIR}/assets/AppIcon.icns" ]; then
    echo "🎨 AppIcon.icns not found, generating from SVG..."
    "${ROOT_DIR}/scripts/generate_icon.sh"
fi

# Step 2: Build release binary for macOS Apple Silicon (arm64)
echo "🔨 Building Release binary for macOS arm64..."
cd "${ROOT_DIR}"
swift build -c release --triple arm64-apple-macosx15.0

BIN_DIR="$(swift build -c release --triple arm64-apple-macosx15.0 --show-bin-path)"
EXECUTABLE_PATH="${BIN_DIR}/Adventurers"
SPARKLE_FRAMEWORK_SRC="${BIN_DIR}/Sparkle.framework"

if [ ! -f "${EXECUTABLE_PATH}" ]; then
    echo "✖ Error: Executable not found at ${EXECUTABLE_PATH}"
    exit 1
fi

if [ ! -d "${SPARKLE_FRAMEWORK_SRC}" ]; then
    echo "✖ Error: Sparkle.framework not found at ${SPARKLE_FRAMEWORK_SRC} (SwiftPM should copy it next to the built binary)"
    exit 1
fi

# Verify architecture is arm64
ARCH_INFO="$(file "${EXECUTABLE_PATH}")"
echo "🔍 Binary Architecture: ${ARCH_INFO}"
if [[ "${ARCH_INFO}" != *"arm64"* ]]; then
    echo "✖ Error: Binary is not arm64!"
    exit 1
fi

# Step 3: Construct .app bundle
echo "📦 Constructing ${APP_NAME}.app bundle..."
rm -rf "${DIST_DIR}"
mkdir -p "${APP_DIR}/Contents/MacOS"
mkdir -p "${APP_DIR}/Contents/Resources"

# Copy executable
cp "${EXECUTABLE_PATH}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"
chmod +x "${APP_DIR}/Contents/MacOS/${APP_NAME}"

# Embed Sparkle.framework (auto-update engine) and point the executable at it. SwiftPM links
# against @loader_path, which resolves relative to Contents/MacOS — that only finds a framework
# sitting next to the binary, not one in Contents/Frameworks, so add the standard app-bundle
# rpath explicitly.
echo "🔧 Embedding Sparkle.framework..."
mkdir -p "${APP_DIR}/Contents/Frameworks"
cp -R "${SPARKLE_FRAMEWORK_SRC}" "${APP_DIR}/Contents/Frameworks/Sparkle.framework"
install_name_tool -add_rpath "@executable_path/../Frameworks" "${APP_DIR}/Contents/MacOS/${APP_NAME}"

# Copy AppIcon
cp "${ROOT_DIR}/assets/AppIcon.icns" "${APP_DIR}/Contents/Resources/AppIcon.icns"
if [ -f "${ROOT_DIR}/assets/AppIcon.png" ]; then
    cp "${ROOT_DIR}/assets/AppIcon.png" "${APP_DIR}/Contents/Resources/AppIcon.png"
fi

# Write Info.plist
cat << PLIST > "${APP_DIR}/Contents/Info.plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>Adventurers</string>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleIconName</key>
    <string>AppIcon</string>
    <key>CFBundleIdentifier</key>
    <string>com.bytecats.adventurers</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key>
    <string>15.0</string>
    <key>LSArchitecturePriority</key>
    <array>
        <string>arm64</string>
    </array>
    <key>NSMicrophoneUsageDescription</key>
    <string>Adventurers Harness uses your microphone for one-click voice dictation into the prompt bar.</string>
    <key>NSSpeechRecognitionUsageDescription</key>
    <string>Adventurers Harness uses Apple Speech recognition for live low-latency speech-to-text dictation.</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSRequiresAquaSystemAppearance</key>
    <false/>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2026 ByteCats. All rights reserved.</string>
    <key>SUFeedURL</key>
    <string>${SPARKLE_FEED_URL}</string>
    <key>SUPublicEDKey</key>
    <string>${SPARKLE_PUBLIC_KEY}</string>
    <key>SUEnableAutomaticChecks</key>
    <true/>
    <key>SUScheduledCheckInterval</key>
    <integer>86400</integer>
</dict>
</plist>
PLIST

# Write PkgInfo
echo -n "APPL????" > "${APP_DIR}/Contents/PkgInfo"

# Step 4: Ad-hoc code signing for local & Apple Silicon execution.
# Sign inside-out (most-nested first): Sparkle.framework bundles two XPC services and a helper
# .app of its own, all of which need their own valid signature before the framework — and in turn
# the outer app — can be sealed. Signing the outer bundle with `--deep` instead of doing this
# explicitly is unreliable for nested XPC services/helper apps, so each layer is signed by hand.
echo "🔏 Signing Sparkle.framework (XPC services, helper app, and framework bundle)..."
FRAMEWORK_DIR="${APP_DIR}/Contents/Frameworks/Sparkle.framework"
for xpc in "${FRAMEWORK_DIR}/Versions/B/XPCServices/"*.xpc; do
    [ -e "${xpc}" ] || continue
    codesign --force --sign - "${xpc}"
done
if [ -d "${FRAMEWORK_DIR}/Versions/B/Updater.app" ]; then
    codesign --force --sign - "${FRAMEWORK_DIR}/Versions/B/Updater.app"
fi
if [ -f "${FRAMEWORK_DIR}/Versions/B/Autoupdate" ]; then
    codesign --force --sign - "${FRAMEWORK_DIR}/Versions/B/Autoupdate"
fi
codesign --force --sign - "${FRAMEWORK_DIR}"

echo "🔏 Signing ${APP_NAME}.app with ad-hoc identity & audio entitlements..."
codesign --force --entitlements "${ROOT_DIR}/entitlements.plist" --sign - "${APP_DIR}"

echo "🔍 Verifying signature..."
codesign --verify --deep --strict "${APP_DIR}"

# Step 5: Package into distributable DMG
echo "💿 Creating DMG installer..."
DMG_PATH="${DIST_DIR}/${APP_NAME}-macOS-arm64.dmg"
hdiutil create -volname "${APP_NAME} Harness" \
    -srcfolder "${APP_DIR}" \
    -ov -format UDZO \
    "${DMG_PATH}"

# Step 6: Package into ZIP and TAR.GZ archives
echo "🗜 Creating ZIP & TAR.GZ distribution archives..."
ZIP_PATH="${DIST_DIR}/${APP_NAME}-macOS-arm64.zip"
TAR_PATH="${DIST_DIR}/${APP_NAME}-macOS-arm64.tar.gz"
cd "${DIST_DIR}"
zip -q -r -y "${ZIP_PATH}" "${APP_NAME}.app"
tar -czf "${TAR_PATH}" "${APP_NAME}.app"

# Step 7: Generate SHA256 checksums
echo "🔒 Computing SHA256 checksums..."
cd "${DIST_DIR}"
shasum -a 256 "${APP_NAME}-macOS-arm64.dmg" > "${APP_NAME}-macOS-arm64.dmg.sha256"
shasum -a 256 "${APP_NAME}-macOS-arm64.zip" > "${APP_NAME}-macOS-arm64.zip.sha256"
shasum -a 256 "${APP_NAME}-macOS-arm64.tar.gz" > "${APP_NAME}-macOS-arm64.tar.gz.sha256"

echo "========================================================="
echo "✔ Successfully packaged Adventurers Harness for macOS ARM64!"
echo "  • App Bundle: ${APP_DIR}"
echo "  • DMG Image:  ${DMG_PATH}"
echo "  • ZIP Archive:${ZIP_PATH}"
echo "  • TAR Archive:${TAR_PATH}"
echo "  • Checksum:   $(cat "${DIST_DIR}/${APP_NAME}-macOS-arm64.dmg.sha256")"
echo "========================================================="
